# -*- coding: utf-8 -*-
"""Copy of website_performance Analysis Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iUTRUOvlHvZWmm0soDzfPO6dBEZkHu3X
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/data-export (1).csv')
df.head(3)

df.columns = df.iloc[0]
df = df.drop(index = 0).reset_index(drop = True)
df.columns = ["channel group" , "Datehour","Users","Sessions","Engaged Sessions","Average engagement time per session","Engaged sessions per user",
              "Events per session","Engagement rate","Event count"]
df.head(3)

df.info()

df['Datehour'] = pd.to_datetime(df['Datehour'] , format = "%Y%m%d%H" , errors = 'coerce')
numeric_cols = df.columns.drop(['channel group' , 'Datehour'])
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric , errors = 'coerce')
df['Hour'] = df['Datehour'].dt.hour
df

df.info()

df.describe()

"""# **Sessions user over Time**

"""

sns.set_style('whitegrid')

plt.figure(figsize=(10,5))
df.groupby('Datehour')[['Sessions' , 'Users']].sum().plot(ax =plt.gca())
plt.title('Sessions and Users over Time')
plt.ylabel('Count')
plt.xlabel('Datehour')
plt.show()

"""# **Total User by channel**"""

plt.figure(figsize =(8,5))
sns.barplot(data =df,x = 'channel group' , y='Users' , estimator=np.sum , palette = 'viridis')
plt.title('Total users by channel')
plt.xticks(rotation =45)
plt.show()

df.head(4)

"""# **Average engagement Time by channel**

"""

plt.figure(figsize = (8,5))
sns.barplot(data =df , x ='channel group', y ='Average engagement time per session' , estimator = np.mean , palette = 'magma')
plt.title('Average engagement Time by channel')
plt.xticks(rotation =45)
plt.show()

"""# **Engagement Rate Distribution by channel**"""

plt.figure(figsize =(8,5))
sns.boxplot(data = df , x ='channel group' , y='Engagement rate' , palette ="coolwarm")
plt.title('Engagement Rate Distribution by channel')
plt.xticks(rotation = 45)
plt.show()

"""# **Engaged vs Non-engaged Session by channel Group**"""

session_df = df.groupby('channel group')[['Sessions' , 'Engaged Sessions',]].sum().reset_index()
session_df['Non-engages'] = session_df['Sessions'] - session_df['Engaged Sessions']
session_df_melted = session_df.melt(id_vars='channel group' ,value_vars =["Engaged Sessions","Non-engages"], var_name='Session Type', value_name='Count')

plt.figure(figsize=(10,6))
sns.barplot(data = session_df_melted , x ='channel group' , y='Count' , hue='Session Type', palette ="viridis")
plt.title('Engaged vs. Non-Engaged Sessions by Channel Group')
plt.xticks(rotation =45)
plt.ylabel('Number of Sessions')
plt.show()

"""# **Traffic by channel and Hour**"""

heatmap_data = df.groupby(['Hour','channel group',])['Sessions'].sum().unstack().fillna(0)

plt.figure(figsize=(15,8))
sns.heatmap(heatmap_data , cmap = 'YlGnBu' , linewidth = 0.5 , annot =True , fmt = '.0f')
plt.title('Traffic by channel and Hour')
plt.xlabel('channel group')
plt.ylabel('Hour of Day')
plt.show()

"""# **Engagement Rate and Session over Time**"""

df_plot = df.groupby('Datehour').agg({
    'Engagement rate': 'mean',
    'Sessions': 'sum'
}).reset_index()

plt.figure(figsize=(12,6))
plt.plot(df_plot['Datehour'] , df_plot['Engagement rate'] , label="Engagement Rate" , color = 'green')
plt.plot(df_plot["Datehour"], df_plot['Sessions'], label ="Sessions", color="blue")
plt.title('Engagement Rate and Sessions over Time')
plt.xlabel("Datehour")
plt.ylabel("Value") # General y-label as scales are different
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()





